version: '{branch}-{build}'
image: Ubuntu

pull_requests:
  do_not_increment_build_number: true

nuget:
  disable_publish_on_pr: true

before_build:
  - choco install dotnet-sdk
  - dotnet restore .\src\Downloader.sln

build_script:
  - dotnet build .\src\Downloader.sln --verbosity minimal

test_script:
  - dotnet test .\src\Downloader.Test\Downloader.Test.csproj
