name: Windows x64

on: [ push ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  build:
    runs-on: windows-latest
    environment: Windows
    strategy:
      matrix:
        dotnet-version: [ 9.0.x ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Build solution
        run: dotnet build -c Release ./src --verbosity minimal 

      - name: Run tests
        run: dotnet test -c Release ./src --verbosity normal --no-build --no-restore